name: Run Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  php-tests:
    runs-on: ubuntu-latest
    continue-on-error: false

    strategy:
      matrix:
        php: [8.2, 8.3, 8.4]
        laravel: [10.*, 11.*,12.*]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
          - laravel: 10.*
            testbench: 8.*
            pest: ^2.34
            pest-plugin: ^2.4
            php: 8.2
          - laravel: 10.*
            testbench: 8.*
            pest: ^2.34
            pest-plugin: ^2.4
            php: 8.3
          - laravel: 10.*
            testbench: 8.*
            pest: ^2.34
            pest-plugin: ^2.4
            php: 8.4
          - laravel: 11.*
            testbench: 9.*
            pest: ^3.7.4
            pest-plugin: ^3.0
            php: 8.2
          - laravel: 11.*
            testbench: 9.*
            pest: ^3.7.4
            pest-plugin: ^3.0
            php: 8.3
          - laravel: 11.*
            testbench: 9.*
            pest: ^3.7.4
            pest-plugin: ^3.0
            php: 8.4
          - laravel: 12.*
            testbench: 10.*
            pest: ^3.7.4
            pest-plugin: ^3.0
            php: 8.2
          - laravel: 12.*
            testbench: 10.*
            pest: ^3.7.4
            pest-plugin: ^3.0
            php: 8.3
          - laravel: 12.*
            testbench: 10.*
            pest: ^3.7.4
            pest-plugin: ^3.0
            php: 8.4

    name: PHP${{ matrix.php }} - Laravel${{ matrix.laravel }} - Testbench${{ matrix.testbench }} - Pest${{ matrix.pest }}  - Pest-Plugin${{ matrix.pest-plugin }} -  ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, mbstring, zip, sqlite, bcmath, soap, intl
          coverage: none

      - name: Install dependencies
        run: |
          composer require --dev \
            "laravel/framework:${{ matrix.laravel }}" \
            "orchestra/testbench:${{ matrix.testbench }}" \
            "pestphp/pest:${{ matrix.pest }}" \
            "pestphp/pest-plugin-laravel:${{ matrix.pest-plugin }}" \
            --no-interaction --no-update

          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Run tests
        run: vendor/bin/pest --ci

  lint-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, dom, curl

      - name: Install Composer dependencies
        run: composer install --no-interaction

      - name: Run Pint for linting
        run: vendor/bin/pint --test

  phpstan-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, dom, curl

      - name: Install Composer dependencies
        run: composer install --no-interaction

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse

